services:
  jni-crontab-sample-app:
    container_name: jni-crontab-sample-app
    image: alpine:latest
    restart: unless-stopped
    command: sh -c "while :; do sleep 1; done"

  cron:
    container_name: jni-docker-crontab
    image: jni-docker-crontab
    restart: always
    depends_on:
      - jni-crontab-sample-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}/jni-docker-crontab-config.json:/opt/crontab/config.json:rw
